version: '3'

services:
    web:
        container_name: iatoswebapp
        restart: always
        build: .
        ports:
            - "80:5000"
        links:
            - iatosapp
    iatosapp:
        container_name: iatosapp
        image: fcernafukuzaki/iatos-docker-tensorflow:latest
        ports: 
            - "5000:5000"
       